export const GLUCOSE_LIST_REQUEST = "GLUCOSE_LIST_REQUEST";
export const GLUCOSE_LIST_SUCCESSS = "GLUCOSE_LIST_SUCCESSS";
export const GLUCOSE_LIST_FAIL = "GLUCOSE_LIST_FAIL";

export const GLUCOSE_DETAILS_REQUEST = "GLUCOSE_DETAILS_REQUEST";
export const GLUCOSE_DETAILS_SUCCESSS = "GLUCOSE_DETAILS_SUCCESSS";
export const GLUCOSE_DETAILS_FAIL = "GLUCOSE_DETAILS_FAIL";
